export const COMPLAINT_DESCRIPTORS: Record<string, string[]> = {
	'Abandoned Bike': ['Chained To Public Property'],
	'Abandoned Vehicle': ['With License Plate'],
	'Air Quality': [
		'Air: Dust, Construction/Demolition (Ae4)',
		'Air: Odor/Fumes, Restaurant (Ad2)',
		'Air: Odor/Fumes, Vehicle Idling (Ad3)',
		'Air: Other Air Problem (Use Comments) (Azz)',
		'Air: Smoke, Chimney Or Vent (As1)',
		'Air: Smoke, Vehicular (Aa4)'
	],
	'Animal In A Park': ['Dead Animal', 'Dog Off Leash', 'Injured Wildlife'],
	'Animal-Abuse': ['Chained', 'Neglected', 'No Shelter', 'OTHER', 'Tortured'],
	Appliance: ['Electric/Gas Range', 'Refrigerator'],
	Asbestos: ['Asbestos Complaint (B1)', 'UNKNOWN'],
	'Best/Site Safety': ['Demolition - Unsafe'],
	'Bike Rack': ['Abandoned Bike'],
	'Bike/Roller/Skate': ['UNKNOWN'],
	'Bike/Roller/Skate Chronic': ['UNKNOWN'],
	'Blocked Driveway': ['No Access', 'Partial Access'],
	Boilers: ['Boiler - Defective/Inoperative/No Permit'],
	'Broken Parking Meter': ['Coin Or Card Did Not Register', 'No Receipt', 'Out Of Order'],
	'Building/Use': [
		'Illegal Conversion Of Residential Building/Space',
		'Illegal. Commercial Use In Resident Zone',
		'No Certificate Of Occupancy/Illegal/Contrary To Co',
		'Sro - Illegal Work/No Permit/Change In Occupancy/Use',
		'Zoning - Non-Conforming/Illegal Vehicle Storage'
	],
	'Bus Stop Shelter Complaint': ['Broken Glass', 'Dirty/Graffiti', 'Snow Removal Requested'],
	'Bus Stop Shelter Placement': ['New Bus Stop Shelter Placement'],
	'Cannabis Retailer': ['Sales To Minors Under 21', 'Suspicious Activity', 'Unlicensed'],
	'Commercial Disposal Complaint': ['Waste Disposal', 'Waste Left In Front Of Residence'],
	'Consumer Complaint': [
		'Barber Shop, Beauty Salon, Or Nail Salon',
		'Bodega, Deli, Or Convenience Store',
		'Car Wash',
		'Clothing, Shoe, Or Accessories Store',
		'Drug Store Or Pharmacy',
		'Garage Or Parking Lot',
		'Home Improvement Contractor',
		'Hotel Or Motel',
		'Landlord Or Real Estate Agent',
		'Laundromat',
		'Other Store (Non-Food)',
		'Restaurant',
		'Stoop Line Stand',
		'Storage Warehouse',
		'Street Fair Vendor',
		'Supermarket Or Grocery Store',
		'Tobacco Sales',
		'Tow Truck Company',
		'Used Car Dealer'
	],
	'Curb Condition': ['Broken Curb', 'Curb Defect-Metal Protruding', 'Defacement'],
	'Damaged Tree': [
		'Branch Cracked And Will Fall',
		'Branch Or Limb Has Fallen Down',
		'Entire Tree Has Fallen Down',
		'Tree Alive - In Poor Condition',
		'Tree Leaning/Uprooted',
		'Tree Trunk Split'
	],
	'Day Care': ['Day Care Facility'],
	'Dead Animal': ['Bird', 'Cat', 'Dog', 'OTHER', 'Opossum', 'Raccoon', 'Rat Or Mouse', 'Squirrel'],
	'Dead/Dying Tree': ['Planted Less Than 2 Years Ago', 'Planted More Than 2 Years Ago'],
	'Derelict Vehicles': ['Derelict Vehicles'],
	'Dirty Condition': [
		'Broken Glass',
		'Debris From Car Accident',
		'Dirt Or Gravel',
		'Dog Waste',
		'Syringes',
		'Trash'
	],
	'Door/Window': ['Door', 'Door Frame', 'Window Frame', 'Window Pane'],
	Drinking: ['After Hours - Licensed Est', 'In Public', 'Underage - Licensed Est'],
	'Drug Activity': ['Use Indoor', 'Use Outside'],
	'Dumpster Complaint': ['Blocking Sidewalk Or Street', 'Overflowing Dumpster'],
	Electric: ['Lighting', 'No Lighting', 'Outlet/Switch', 'Power Outage', 'Wiring'],
	Electrical: ['Electrical Wiring Defective/Exposed'],
	Elevator: [
		'Elevator - Multiple Devices On Property',
		'Elevator - Single Device On Property/No Alternate Service',
		'Maintenance'
	],
	'Emergency Response Team (Ert)': [
		'After Hours Work - Illegal',
		'Lights From Parking Lot Shining On Building'
	],
	Encampment: ['UNKNOWN'],
	'Flooring/Stairs': ['Floor', 'Stairs'],
	'Food Establishment': [
		'Bare Hands In Contact W/ Food',
		'Food Contains Foreign Object',
		'Food Contaminated',
		'Food Spoiled',
		'Food Temperature',
		'Food Worker Hygiene',
		'Kitchen/Food Prep Area',
		'Letter Grading',
		'No Permit Or License',
		'Pet/Animal',
		'Rodents/Insects/Garbage'
	],
	'Food Poisoning': ['1 Or 2', '3 Or More'],
	'For Hire Vehicle Complaint': [
		'Driver Complaint - Non Passenger',
		'Driver Complaint - Passenger'
	],
	General: [
		'Bell/Buzzer/Intercom',
		'Cabinet',
		'Cooking Gas',
		'Janitor/Super',
		'Mailbox',
		'Signage Missing',
		'Ventilation System'
	],
	'General Construction/Plumbing': [
		'Adjacent Buildings Not Protected',
		'Building - Vacant, Open And Unguarded',
		'Building Permit - None',
		'Building Shaking/Vibrating/Structural Stability',
		'Cons - Contrary/Beyond Approved Plans/Permits',
		'Curb Cut/Driveway/Carport - Illegal',
		'Debris - Excessive',
		'Debris - Falling Or In Danger Of Falling',
		'Egress - Doors Locked/Blocked/Improper/No Secondary Means',
		'Failure To Maintain',
		'Fence - None/Inadequate',
		'Posted Notice Or Order Removed/Tampered With',
		'Sidewalk Shed/Pipe Scafford - Inadequate Defective/None',
		'Site Conditions Endangering Workers',
		'Vent/Exhaust - Illegal/Improper',
		'Wall/Retaining Wall - Bulging/Cracked',
		'Working Contrary To Stop Work Order'
	],
	Graffiti: ['Graffiti', 'Police Report Not Requested'],
	'Hazardous Materials': ['Chemical Odor (Hd1)', 'Chemical Spill/Release (Ha1)'],
	'Heat/Hot Water': ['Apartment Only', 'Entire Building'],
	'Homeless Person Assistance': ['Chronic', 'Non-Chronic'],
	'Illegal Dumping': ['Chronic Dumping', 'Removal Request'],
	'Illegal Fireworks': ['UNKNOWN'],
	'Illegal Parking': [
		'Blocked Bike Lane',
		'Blocked Crosswalk',
		'Blocked Hydrant',
		'Blocked Sidewalk',
		'Commercial Overnight Parking',
		'Detached Trailer',
		'Double Parked Blocking Traffic',
		'Double Parked Blocking Vehicle',
		'License Plate Obscured',
		'Overnight Commercial Storage',
		'Paper License Plates',
		'Parking Permit Improper Use',
		'Posted Parking Sign Violation',
		'Unauthorized Bus Layover'
	],
	'Illegal Posting': ['Flyer Or Handbill', 'Poster Or Sign', 'Sticker Or Decal'],
	'Illegal Tree Damage': [
		'Bicycle Chained To Tree',
		'Branches Damaged',
		'Roots Damaged',
		'Trunk Damaged',
		'Unauthorized Tree Pruning',
		'Unauthorized Tree Removal'
	],
	'Indoor Air Quality': [
		'Chemical Vapors/Gases/Odors',
		'Dust From Construction',
		'OTHER',
		'Sewage Odor',
		'Ventilation'
	],
	'Indoor Sewage': ['Sewage Leak'],
	'Investigations And Discipline (Iad)': ['Investigative Inspection'],
	Lead: ['Lead Kit Request (Residential) (L10)'],
	'Litter Basket Complaint': ['Overflowing'],
	'Litter Basket Request': ['New Basket', 'Replacement Basket'],
	'Lost Property': ['Bag/Wallet', 'Clothing/Glasses', 'Electronics/Phones', 'OTHER'],
	'Maintenance Or Facility': [
		'Garbage Or Litter',
		'Graffiti Or Vandalism',
		'Grass/Weeds',
		'Hours Of Operation',
		'Rodent Sighting',
		'Snow Or Ice',
		'Structure - Indoors',
		'Structure - Outdoors',
		'Unsecured Facility'
	],
	'Missed Collection': [
		'Bulky Recycling',
		'Bulky Trash',
		'Compost',
		'Recycling - Metal/Glass/Rigid Plastic',
		'Recycling - Paper',
		'Recycling - Paper/Metal/Glass/Rigid Plastic',
		'Trash',
		'Trash And Bulky Trash'
	],
	'Mobile Food Vendor': [
		'Equipment',
		'Food Source/Protection',
		'Food Temperature',
		'Food Worker Activity'
	],
	Mold: ['Public Complaint - Comm Location'],
	'New Tree Request': ['For One Address'],
	Noise: [
		'Noise, Barking Dog (Nr5)',
		'Noise, Ice Cream Truck (Nr4)',
		'Noise, Other Animals (Nr6)',
		'Noise:  Lawn Care Equipment (Ncl)',
		'Noise: Air Condition/Ventilation Equipment (Nv1)',
		'Noise: Alarms (Nr3)',
		'Noise: Boat(Engine,Music,Etc) (Nr10)',
		'Noise: Construction Before/After Hours (Nm1)',
		'Noise: Construction Equipment (Nc1)',
		'Noise: Jack Hammering (Nc2)',
		'Noise: Manufacturing Noise (Nk1)',
		'Noise: Private Carting Noise (Nq1)'
	],
	'Noise - Commercial': [
		'Banging/Pounding',
		'Car/Truck Horn',
		'Car/Truck Music',
		'Loud Music/Party',
		'Loud Talking'
	],
	'Noise - House Of Worship': ['Loud Music/Party', 'Loud Talking'],
	'Noise - Park': ['Loud Music/Party', 'Loud Talking'],
	'Noise - Residential': [
		'Banging/Pounding',
		'Loud Music/Party',
		'Loud Talking',
		'Loud Television'
	],
	'Noise - Street/Sidewalk': ['Loud Music/Party', 'Loud Talking'],
	'Noise - Vehicle': ['Car/Truck Horn', 'Car/Truck Music', 'Engine Idling'],
	'Non-Emergency Police Matter': ['OTHER', 'Trespassing'],
	'Non-Residential Heat': ['Inadequate Or No Heat'],
	Obstruction: [
		'Cone',
		'Merchandise',
		'Sidewalk Display',
		'Sign',
		'Trash Or Recycling',
		'Weeds Or Grass'
	],
	'Outdoor Dining': ['Restaurant Status', 'Sidewalk Zone Blocked', 'Site Setup Condition'],
	'Outside Building': ['Pavement', 'Roofing'],
	'Overgrown Tree/Branches': [
		'Blocking Street',
		'Dead Branches In Tree',
		'Hitting Building',
		'Hitting Phone/Cable Lines',
		'Hitting Power Lines',
		'Traffic Sign Or Signal Blocked'
	],
	'Paint/Plaster': ['Cabinet', 'Ceiling', 'Door/Frame', 'Radiator', 'Wall', 'Window/Frame'],
	Panhandling: ['UNKNOWN'],
	Plumbing: [
		'Basin/Sink',
		'Bathtub/Shower',
		'Failure To Retain Water/Improper Drainage- (Ll103/89)',
		'Gas Hook-Up/Piping - Illegal Or Defective',
		'Plumbing Work - Illegal/No Permit/Standpipe/Sprinkler',
		'Plumbing-Defective/Leaking/Not Maintained',
		'Radiator',
		'Steam Pipe/Riser',
		'Toilet',
		'Water Supply'
	],
	'Real Time Enforcement': ['Work Without A Permit - Occupied Multiple Dwelling'],
	'Residential Disposal Complaint': [
		'Bin Not Used',
		'Mattress Or Box Spring Uncovered',
		'Storage Area Not Provided',
		'Trash Or Recycling Not Secure',
		'Waste Left In Front Of Other Residence',
		'Waste Not Separated',
		'Waste Set Out Too Early Or Too Late'
	],
	Rodent: ['Condition Attracting Rodents', 'Rat Sighting', 'Signs Of Rodents'],
	'Root/Sewer/Sidewalk Condition': ['Trees And Sidewalks Program'],
	Safety: [
		'Carbon Monoxide Detector',
		'Fire Escape',
		'Smoke Detector',
		'Sprinkler',
		'Window Guard Broken/Missing'
	],
	'Sanitation Worker Or Vehicle Complaint': [
		'Inappropriate Behavior',
		'Noise',
		'Spilled Garbage',
		'Unsafe Driving'
	],
	'School Maintenance': ['Heating Problem', 'Snow/Ice'],
	Sewer: [
		'Catch Basin Clogged/Flooding (Use Comments) (Sc)',
		'Catch Basin Search (Sc2)',
		'Catch Basin Sunken/Damaged/Raised (Sc1)',
		'Culvert Blocked/Needs Cleaning (Se)',
		'Manhole Cover Missing (Emergency) (Sa3)',
		'Manhole Overflow (Use Comments) (Sa1)',
		'Rain Garden Debris (Girgd)',
		'Sewer Backup (Use Comments) (Sa)',
		'Sewer Odor (Sa2)',
		'Street Flooding (Sj)'
	],
	'Sidewalk Condition': [
		'Blocked - Construction',
		'Broken Sidewalk',
		'Defective Hardware',
		'Dumpster - Construction Waste',
		'Pedestrian Ramp Defective',
		'Sidewalk Collapsed',
		'Sidewalk Violation'
	],
	'Smoking Or Vaping': ['Allowed In Smoke Free Area'],
	'Snow Or Ice': ['Pedestrian Feature', 'Roadway', 'Sidewalk', 'Snow Tracking'],
	'Special Projects Inspection Team (Spit)': [
		'Advertising Sign/Billboard/Posters/Flexible Fabric - Illegal',
		'Illegal Hotel Rooms In Residential Building',
		'Sign/Awning/Marquee - Illegal/No Permit'
	],
	'Street Condition': [
		'Blocked - Construction',
		'Cave-In',
		'Defective Hardware',
		'Dumpster - Construction Waste',
		'Failed Street Repair',
		'Plate Condition - Noisy',
		'Plate Condition - Shifted',
		'Pothole',
		'Rough, Pitted Or Cracked Roads'
	],
	'Street Light Condition': [
		'Fixture/Luminaire Hanging',
		'Lamppost Base Door/Cover Open',
		'Lamppost Damaged',
		'Lamppost Knocked Down',
		'Lamppost Wire Exposed',
		'Multiple Street Lights Out',
		'Street Light Cycling',
		'Street Light Dayburning',
		'Street Light Lamp Dim',
		'Street Light Lamp Missing',
		'Street Light Out',
		'Traffic Signal Light'
	],
	'Street Sign - Damaged': [
		'Bus Stop',
		'No Parking, Standing, Stopping',
		'One Way',
		'St Name - Attached To Pole',
		'Stop',
		'Street Cleaning - Asp',
		'UNKNOWN'
	],
	'Street Sign - Dangling': [
		'No Parking, Standing, Stopping',
		'St Name - Attached To Pole',
		'Stop',
		'Street Cleaning - Asp',
		'UNKNOWN'
	],
	'Street Sign - Missing': [
		'No Parking, Standing, Stopping',
		'St Name - Attached To Pole',
		'Stop',
		'UNKNOWN'
	],
	'Street Sweeping Complaint': ['Inadequate Sweeping', 'Street Not Swept'],
	'Taxi Complaint': ['Driver Complaint - Non Passenger', 'Driver Complaint - Passenger'],
	Traffic: [
		'Chronic Speeding',
		'Chronic Stoplight Violation',
		'Congestion/Gridlock',
		'Drag Racing',
		'Truck Route Violation'
	],
	'Traffic Signal Condition': [
		'Aps',
		'Base Door',
		'Bike Signal',
		'Cable',
		'Controller',
		'Led Pedestrian Unit',
		'Ped Lamp',
		'Ped Multiple Lamps',
		'Pedestrian Signal',
		'Post',
		'Time Switch',
		'Underground',
		'Veh Sgnl Mult Lamps',
		'Veh Signal Head',
		'Veh Signal Lamp',
		'Veh Signal Lens',
		'Veh Signal Visor',
		'Vehicle Signal',
		'Wireless'
	],
	'Unleashed Dog': ['Unleashed Dog In Public'],
	'Unsanitary Animal Pvt Property': ['Dog'],
	'Unsanitary Condition': ['Garbage/Recycling Storage', 'Mold', 'Pests', 'Sewage'],
	'Urinating In Public': ['UNKNOWN'],
	'Vendor Enforcement': ['Food Vendor', 'Non-Food Vendor'],
	'Violation Of Park Rules': [
		'Bbq Outside Authorized Area',
		'Obstructing Public Use',
		'Smoking',
		'Unlicensed Vendors',
		'Unsafe Use Of Playground'
	],
	'Water Conservation': [
		'Illegal Use Of A Hydrant (Cin)',
		'Water Meter Broken/Leaking - Other (Cmo)',
		'Water Meter Broken/Leaking - Private Residence (Cmr)'
	],
	'Water Leak': ['Damp Spot', 'Heavy Flow', 'Slow Leak'],
	'Water System': [
		'Dirty Water (We)',
		'Excessive Water In Basement (Wefb)',
		'Hyd Valve Box Cover Missing (Wv2)',
		'Hydrant Defective (Wc2)',
		'Hydrant Knocked Over/Missing (Wc)',
		'Hydrant Leaking (Wc1)',
		'Hydrant Running (Wc3)',
		'Hydrant Running Full (Wa4)',
		'Leak (Use Comments) (Wa2)',
		'Low Water Pressure - Wlwp',
		'No Water (Wnw)',
		'Possible Water Main Break (Use Comments) (Wa1)'
	],
	'Wood Pile Remaining': ['Remove Debris']
};

export const DESCRIPTOR_LOCATIONS: Record<string, string[]> = {
	'Abandoned Bike|Chained To Public Property': ['Street'],
	'Abandoned Vehicle|With License Plate': ['Street/Sidewalk'],
	'Air Quality|Air: Dust, Construction/Demolition (Ae4)': ['UNKNOWN'],
	'Air Quality|Air: Odor/Fumes, Restaurant (Ad2)': ['UNKNOWN'],
	'Air Quality|Air: Odor/Fumes, Vehicle Idling (Ad3)': ['UNKNOWN'],
	'Air Quality|Air: Other Air Problem (Use Comments) (Azz)': ['UNKNOWN'],
	'Air Quality|Air: Smoke, Chimney Or Vent (As1)': ['UNKNOWN'],
	'Air Quality|Air: Smoke, Vehicular (Aa4)': ['UNKNOWN'],
	'Animal In A Park|Dead Animal': ['Park'],
	'Animal In A Park|Dog Off Leash': ['Park'],
	'Animal In A Park|Injured Wildlife': ['Park'],
	'Animal-Abuse|Chained': ['Residential Building/House'],
	'Animal-Abuse|Neglected': ['Residential Building/House', 'Store/Commercial'],
	'Animal-Abuse|No Shelter': ['House And Store', 'Residential Building'],
	'Animal-Abuse|OTHER': ['Residential Building/House', 'Street/Sidewalk'],
	'Animal-Abuse|Tortured': ['Residential Building/House'],
	'Appliance|Electric/Gas Range': ['Residential Building'],
	'Appliance|Refrigerator': ['Residential Building'],
	'Asbestos|Asbestos Complaint (B1)': ['UNKNOWN'],
	'Asbestos|UNKNOWN': ['3+ Family Apartment Building'],
	'Best/Site Safety|Demolition - Unsafe': ['UNKNOWN'],
	'Bike Rack|Abandoned Bike': ['Sidewalk'],
	'Bike/Roller/Skate Chronic|UNKNOWN': ['Street/Sidewalk'],
	'Bike/Roller/Skate|UNKNOWN': ['Street/Sidewalk'],
	'Blocked Driveway|No Access': ['Street/Sidewalk'],
	'Blocked Driveway|Partial Access': ['Street/Sidewalk'],
	'Boilers|Boiler - Defective/Inoperative/No Permit': ['UNKNOWN'],
	'Broken Parking Meter|Coin Or Card Did Not Register': ['Street'],
	'Broken Parking Meter|No Receipt': ['Street'],
	'Broken Parking Meter|Out Of Order': ['Street'],
	'Building/Use|Illegal Conversion Of Residential Building/Space': ['UNKNOWN'],
	'Building/Use|Illegal. Commercial Use In Resident Zone': ['UNKNOWN'],
	'Building/Use|No Certificate Of Occupancy/Illegal/Contrary To Co': ['UNKNOWN'],
	'Building/Use|Sro - Illegal Work/No Permit/Change In Occupancy/Use': ['UNKNOWN'],
	'Building/Use|Zoning - Non-Conforming/Illegal Vehicle Storage': ['UNKNOWN'],
	'Bus Stop Shelter Complaint|Broken Glass': ['Bus Stop Shelter'],
	'Bus Stop Shelter Complaint|Dirty/Graffiti': ['Bus Stop Shelter'],
	'Bus Stop Shelter Complaint|Snow Removal Requested': ['Bus Stop Shelter'],
	'Bus Stop Shelter Placement|New Bus Stop Shelter Placement': ['Bus Stop Shelter'],
	'Cannabis Retailer|Sales To Minors Under 21': ['UNKNOWN'],
	'Cannabis Retailer|Suspicious Activity': ['UNKNOWN'],
	'Cannabis Retailer|Unlicensed': ['UNKNOWN'],
	'Commercial Disposal Complaint|Waste Disposal': ['Sidewalk'],
	'Commercial Disposal Complaint|Waste Left In Front Of Residence': ['Sidewalk'],
	'Consumer Complaint|Barber Shop, Beauty Salon, Or Nail Salon': ['Business'],
	'Consumer Complaint|Bodega, Deli, Or Convenience Store': ['Business'],
	'Consumer Complaint|Car Wash': ['Business'],
	'Consumer Complaint|Clothing, Shoe, Or Accessories Store': ['Business'],
	'Consumer Complaint|Drug Store Or Pharmacy': ['Business'],
	'Consumer Complaint|Garage Or Parking Lot': ['Business'],
	'Consumer Complaint|Home Improvement Contractor': ['Business'],
	'Consumer Complaint|Hotel Or Motel': ['Business'],
	'Consumer Complaint|Landlord Or Real Estate Agent': ['Business'],
	'Consumer Complaint|Laundromat': ['Business'],
	'Consumer Complaint|Other Store (Non-Food)': ['Business'],
	'Consumer Complaint|Restaurant': ['Business'],
	'Consumer Complaint|Stoop Line Stand': ['Business'],
	'Consumer Complaint|Storage Warehouse': ['Business'],
	'Consumer Complaint|Street Fair Vendor': ['Business'],
	'Consumer Complaint|Supermarket Or Grocery Store': ['Business'],
	'Consumer Complaint|Tobacco Sales': ['Business'],
	'Consumer Complaint|Tow Truck Company': ['Business'],
	'Consumer Complaint|Used Car Dealer': ['Business'],
	'Curb Condition|Broken Curb': ['Sidewalk'],
	'Curb Condition|Curb Defect-Metal Protruding': ['Sidewalk'],
	'Curb Condition|Defacement': ['Curb'],
	'Damaged Tree|Branch Cracked And Will Fall': ['Street'],
	'Damaged Tree|Branch Or Limb Has Fallen Down': ['Street'],
	'Damaged Tree|Entire Tree Has Fallen Down': ['Street'],
	'Damaged Tree|Tree Alive - In Poor Condition': ['Street'],
	'Damaged Tree|Tree Leaning/Uprooted': ['Street'],
	'Damaged Tree|Tree Trunk Split': ['Street'],
	'Day Care|Day Care Facility': ['Apartment', 'Commercial Building', 'OTHER', 'Private School'],
	'Dead Animal|Bird': ['Sidewalk', 'Street'],
	'Dead Animal|Cat': ['Sidewalk', 'Street'],
	'Dead Animal|Dog': ['Sidewalk'],
	'Dead Animal|OTHER': ['Street'],
	'Dead Animal|Opossum': ['Street'],
	'Dead Animal|Raccoon': ['Sidewalk', 'Street'],
	'Dead Animal|Rat Or Mouse': ['Sidewalk', 'Street'],
	'Dead Animal|Squirrel': ['Sidewalk', 'Street'],
	'Dead/Dying Tree|Planted Less Than 2 Years Ago': ['Street'],
	'Dead/Dying Tree|Planted More Than 2 Years Ago': ['Street'],
	'Derelict Vehicles|Derelict Vehicles': ['Street'],
	'Dirty Condition|Broken Glass': ['Sidewalk', 'Street'],
	'Dirty Condition|Debris From Car Accident': ['Street'],
	'Dirty Condition|Dirt Or Gravel': ['Street'],
	'Dirty Condition|Dog Waste': ['Sidewalk'],
	'Dirty Condition|Syringes': ['Sidewalk'],
	'Dirty Condition|Trash': ['Alley', 'Gutter', 'Sidewalk', 'Street', 'Yard'],
	'Door/Window|Door': ['Residential Building'],
	'Door/Window|Door Frame': ['Residential Building'],
	'Door/Window|Window Frame': ['Residential Building'],
	'Door/Window|Window Pane': ['Residential Building'],
	'Drinking|After Hours - Licensed Est': ['Club/Bar/Restaurant'],
	'Drinking|In Public': ['Residential Building/House', 'Store/Commercial', 'Street/Sidewalk'],
	'Drinking|Underage - Licensed Est': ['Club/Bar/Restaurant'],
	'Drug Activity|Use Indoor': ['Common Area', 'Hallway', 'Lobby', 'OTHER', 'Stairwell'],
	'Drug Activity|Use Outside': ['Street/Sidewalk'],
	'Dumpster Complaint|Blocking Sidewalk Or Street': ['Sidewalk', 'Street'],
	'Dumpster Complaint|Overflowing Dumpster': ['Sidewalk', 'Street'],
	'Electrical|Electrical Wiring Defective/Exposed': ['UNKNOWN'],
	'Electric|Lighting': ['Residential Building'],
	'Electric|No Lighting': ['Residential Building'],
	'Electric|Outlet/Switch': ['Residential Building'],
	'Electric|Power Outage': ['Residential Building'],
	'Electric|Wiring': ['Residential Building'],
	'Elevator|Elevator - Multiple Devices On Property': ['UNKNOWN'],
	'Elevator|Elevator - Single Device On Property/No Alternate Service': ['UNKNOWN'],
	'Elevator|Maintenance': ['Residential Building'],
	'Emergency Response Team (Ert)|After Hours Work - Illegal': ['UNKNOWN'],
	'Emergency Response Team (Ert)|Lights From Parking Lot Shining On Building': ['UNKNOWN'],
	'Encampment|UNKNOWN': [
		'Park/Playground',
		'Residential Building/House',
		'Store/Commercial',
		'Street/Sidewalk',
		'Subway'
	],
	'Flooring/Stairs|Floor': ['Residential Building'],
	'Flooring/Stairs|Stairs': ['Residential Building'],
	'Food Establishment|Bare Hands In Contact W/ Food': ['Restaurant/Bar/Deli/Bakery'],
	'Food Establishment|Food Contains Foreign Object': ['Restaurant/Bar/Deli/Bakery'],
	'Food Establishment|Food Contaminated': ['Restaurant/Bar/Deli/Bakery'],
	'Food Establishment|Food Spoiled': ['Restaurant/Bar/Deli/Bakery'],
	'Food Establishment|Food Temperature': ['Restaurant/Bar/Deli/Bakery'],
	'Food Establishment|Food Worker Hygiene': ['Restaurant/Bar/Deli/Bakery'],
	'Food Establishment|Kitchen/Food Prep Area': ['Restaurant/Bar/Deli/Bakery'],
	'Food Establishment|Letter Grading': ['Restaurant/Bar/Deli/Bakery'],
	'Food Establishment|No Permit Or License': ['Restaurant/Bar/Deli/Bakery'],
	'Food Establishment|Pet/Animal': ['Restaurant/Bar/Deli/Bakery'],
	'Food Establishment|Rodents/Insects/Garbage': ['Restaurant/Bar/Deli/Bakery'],
	'Food Poisoning|1 Or 2': ['OTHER', 'Restaurant/Bar/Deli/Bakery'],
	'Food Poisoning|3 Or More': ['Restaurant/Bar/Deli/Bakery'],
	'For Hire Vehicle Complaint|Driver Complaint - Non Passenger': ['Street', 'UNKNOWN'],
	'For Hire Vehicle Complaint|Driver Complaint - Passenger': ['Street'],
	'General Construction/Plumbing|Adjacent Buildings Not Protected': ['UNKNOWN'],
	'General Construction/Plumbing|Building - Vacant, Open And Unguarded': ['UNKNOWN'],
	'General Construction/Plumbing|Building Permit - None': ['UNKNOWN'],
	'General Construction/Plumbing|Building Shaking/Vibrating/Structural Stability': ['UNKNOWN'],
	'General Construction/Plumbing|Cons - Contrary/Beyond Approved Plans/Permits': ['UNKNOWN'],
	'General Construction/Plumbing|Curb Cut/Driveway/Carport - Illegal': ['UNKNOWN'],
	'General Construction/Plumbing|Debris - Excessive': ['UNKNOWN'],
	'General Construction/Plumbing|Debris - Falling Or In Danger Of Falling': ['UNKNOWN'],
	'General Construction/Plumbing|Egress - Doors Locked/Blocked/Improper/No Secondary Means': [
		'UNKNOWN'
	],
	'General Construction/Plumbing|Failure To Maintain': ['UNKNOWN'],
	'General Construction/Plumbing|Fence - None/Inadequate': ['UNKNOWN'],
	'General Construction/Plumbing|Posted Notice Or Order Removed/Tampered With': ['UNKNOWN'],
	'General Construction/Plumbing|Sidewalk Shed/Pipe Scafford - Inadequate Defective/None': [
		'UNKNOWN'
	],
	'General Construction/Plumbing|Site Conditions Endangering Workers': ['UNKNOWN'],
	'General Construction/Plumbing|Vent/Exhaust - Illegal/Improper': ['UNKNOWN'],
	'General Construction/Plumbing|Wall/Retaining Wall - Bulging/Cracked': ['UNKNOWN'],
	'General Construction/Plumbing|Working Contrary To Stop Work Order': ['UNKNOWN'],
	'General|Bell/Buzzer/Intercom': ['Residential Building'],
	'General|Cabinet': ['Residential Building'],
	'General|Cooking Gas': ['Residential Building'],
	'General|Janitor/Super': ['Residential Building'],
	'General|Mailbox': ['Residential Building'],
	'General|Signage Missing': ['Residential Building'],
	'General|Ventilation System': ['Residential Building'],
	'Graffiti|Graffiti': ['Comercial', 'Mixed Use', 'Residential', 'UNKNOWN'],
	'Graffiti|Police Report Not Requested': ['Store/Commercial', 'Street/Sidewalk'],
	'Hazardous Materials|Chemical Odor (Hd1)': ['UNKNOWN'],
	'Hazardous Materials|Chemical Spill/Release (Ha1)': ['UNKNOWN'],
	'Heat/Hot Water|Apartment Only': ['Residential Building'],
	'Heat/Hot Water|Entire Building': ['Residential Building'],
	'Homeless Person Assistance|Chronic': [
		'OTHER',
		'Park/Playground',
		'Residential Building/House',
		'Store/Commercial',
		'Street/Sidewalk',
		'Subway'
	],
	'Homeless Person Assistance|Non-Chronic': [
		'House Of Worship',
		'OTHER',
		'Park/Playground',
		'Residential Building/House',
		'Store/Commercial',
		'Street/Sidewalk',
		'Subway'
	],
	'Illegal Dumping|Chronic Dumping': ['Sidewalk', 'Street'],
	'Illegal Dumping|Removal Request': ['Sidewalk', 'Street'],
	'Illegal Fireworks|UNKNOWN': ['Park/Playground', 'Residential Building/House', 'Street/Sidewalk'],
	'Illegal Parking|Blocked Bike Lane': ['Street/Sidewalk'],
	'Illegal Parking|Blocked Crosswalk': ['Street/Sidewalk'],
	'Illegal Parking|Blocked Hydrant': ['Street/Sidewalk'],
	'Illegal Parking|Blocked Sidewalk': ['Street/Sidewalk'],
	'Illegal Parking|Commercial Overnight Parking': ['Street/Sidewalk'],
	'Illegal Parking|Detached Trailer': ['Street/Sidewalk'],
	'Illegal Parking|Double Parked Blocking Traffic': ['Street/Sidewalk'],
	'Illegal Parking|Double Parked Blocking Vehicle': ['Street/Sidewalk'],
	'Illegal Parking|License Plate Obscured': ['Street/Sidewalk'],
	'Illegal Parking|Overnight Commercial Storage': ['Street/Sidewalk'],
	'Illegal Parking|Paper License Plates': ['Street/Sidewalk'],
	'Illegal Parking|Parking Permit Improper Use': ['Street/Sidewalk'],
	'Illegal Parking|Posted Parking Sign Violation': ['Street/Sidewalk'],
	'Illegal Parking|Unauthorized Bus Layover': ['Street/Sidewalk'],
	'Illegal Posting|Flyer Or Handbill': ['Sidewalk'],
	'Illegal Posting|Poster Or Sign': ['Sidewalk', 'Street'],
	'Illegal Posting|Sticker Or Decal': ['Sidewalk'],
	'Illegal Tree Damage|Bicycle Chained To Tree': ['Street'],
	'Illegal Tree Damage|Branches Damaged': ['Street'],
	'Illegal Tree Damage|Roots Damaged': ['Street'],
	'Illegal Tree Damage|Trunk Damaged': ['Street'],
	'Illegal Tree Damage|Unauthorized Tree Pruning': ['Street'],
	'Illegal Tree Damage|Unauthorized Tree Removal': ['Street'],
	'Indoor Air Quality|Chemical Vapors/Gases/Odors': ['3+ Family Apartment Building'],
	'Indoor Air Quality|Dust From Construction': ['3+ Family Apartment Building'],
	'Indoor Air Quality|OTHER': ['3+ Family Apartment Building'],
	'Indoor Air Quality|Sewage Odor': ['1-2 Family Dwelling', '3+ Family Apt. Building'],
	'Indoor Air Quality|Ventilation': ['3+ Family Apartment Building'],
	'Indoor Sewage|Sewage Leak': ['3+ Family Apt. Building'],
	'Investigations And Discipline (Iad)|Investigative Inspection': ['UNKNOWN'],
	'Lead|Lead Kit Request (Residential) (L10)': ['UNKNOWN'],
	'Litter Basket Complaint|Overflowing': ['Sidewalk'],
	'Litter Basket Request|New Basket': ['Sidewalk', 'Street'],
	'Litter Basket Request|Replacement Basket': ['Street'],
	'Lost Property|Bag/Wallet': ['Taxi'],
	'Lost Property|Clothing/Glasses': ['Taxi'],
	'Lost Property|Electronics/Phones': ['Taxi'],
	'Lost Property|OTHER': ['Taxi'],
	'Maintenance Or Facility|Garbage Or Litter': ['Park', 'Street/Curbside'],
	'Maintenance Or Facility|Graffiti Or Vandalism': ['Park'],
	'Maintenance Or Facility|Grass/Weeds': ['Park'],
	'Maintenance Or Facility|Hours Of Operation': ['Park'],
	'Maintenance Or Facility|Rodent Sighting': ['Park', 'Street/Curbside'],
	'Maintenance Or Facility|Snow Or Ice': ['Park', 'Street/Curbside'],
	'Maintenance Or Facility|Structure - Indoors': ['Park'],
	'Maintenance Or Facility|Structure - Outdoors': ['Park', 'Street/Curbside'],
	'Maintenance Or Facility|Unsecured Facility': ['Park'],
	'Missed Collection|Bulky Recycling': ['Street'],
	'Missed Collection|Bulky Trash': ['Street'],
	'Missed Collection|Compost': ['Street'],
	'Missed Collection|Recycling - Metal/Glass/Rigid Plastic': ['Street'],
	'Missed Collection|Recycling - Paper': ['Street'],
	'Missed Collection|Recycling - Paper/Metal/Glass/Rigid Plastic': ['Street'],
	'Missed Collection|Trash': ['Street'],
	'Missed Collection|Trash And Bulky Trash': ['Street'],
	'Mobile Food Vendor|Equipment': ['Mobile Food Vendor'],
	'Mobile Food Vendor|Food Source/Protection': ['Mobile Food Vendor'],
	'Mobile Food Vendor|Food Temperature': ['Mobile Food Vendor'],
	'Mobile Food Vendor|Food Worker Activity': ['Mobile Food Vendor'],
	'Mold|Public Complaint - Comm Location': ['Commercial Building'],
	'New Tree Request|For One Address': ['Street'],
	'Noise - Commercial|Banging/Pounding': ['Club/Bar/Restaurant', 'Store/Commercial'],
	'Noise - Commercial|Car/Truck Horn': ['Store/Commercial'],
	'Noise - Commercial|Car/Truck Music': ['Store/Commercial'],
	'Noise - Commercial|Loud Music/Party': ['Club/Bar/Restaurant', 'Store/Commercial'],
	'Noise - Commercial|Loud Talking': ['Club/Bar/Restaurant', 'Store/Commercial'],
	'Noise - House Of Worship|Loud Music/Party': ['House Of Worship'],
	'Noise - House Of Worship|Loud Talking': ['House Of Worship'],
	'Noise - Park|Loud Music/Party': ['Park/Playground'],
	'Noise - Park|Loud Talking': ['Park/Playground'],
	'Noise - Residential|Banging/Pounding': ['Residential Building/House'],
	'Noise - Residential|Loud Music/Party': ['Residential Building/House'],
	'Noise - Residential|Loud Talking': ['Residential Building/House'],
	'Noise - Residential|Loud Television': ['Residential Building/House'],
	'Noise - Street/Sidewalk|Loud Music/Party': ['Street/Sidewalk'],
	'Noise - Street/Sidewalk|Loud Talking': ['Street/Sidewalk'],
	'Noise - Vehicle|Car/Truck Horn': ['Street/Sidewalk'],
	'Noise - Vehicle|Car/Truck Music': ['Street/Sidewalk'],
	'Noise - Vehicle|Engine Idling': ['Street/Sidewalk'],
	'Noise|Noise, Barking Dog (Nr5)': ['UNKNOWN'],
	'Noise|Noise, Ice Cream Truck (Nr4)': ['UNKNOWN'],
	'Noise|Noise, Other Animals (Nr6)': ['UNKNOWN'],
	'Noise|Noise:  Lawn Care Equipment (Ncl)': ['UNKNOWN'],
	'Noise|Noise: Air Condition/Ventilation Equipment (Nv1)': ['UNKNOWN'],
	'Noise|Noise: Alarms (Nr3)': ['UNKNOWN'],
	'Noise|Noise: Boat(Engine,Music,Etc) (Nr10)': ['UNKNOWN'],
	'Noise|Noise: Construction Before/After Hours (Nm1)': ['UNKNOWN'],
	'Noise|Noise: Construction Equipment (Nc1)': ['UNKNOWN'],
	'Noise|Noise: Jack Hammering (Nc2)': ['UNKNOWN'],
	'Noise|Noise: Manufacturing Noise (Nk1)': ['UNKNOWN'],
	'Noise|Noise: Private Carting Noise (Nq1)': ['UNKNOWN'],
	'Non-Emergency Police Matter|OTHER': [
		'Park/Playground',
		'Residential Building/House',
		'Store/Commercial',
		'Street/Sidewalk'
	],
	'Non-Emergency Police Matter|Trespassing': [
		'Residential Building/House',
		'Store/Commercial',
		'Street/Sidewalk'
	],
	'Non-Residential Heat|Inadequate Or No Heat': ['Building (Non-Residential)'],
	'Obstruction|Cone': ['Sidewalk', 'Street'],
	'Obstruction|Merchandise': ['Sidewalk', 'Street'],
	'Obstruction|Sidewalk Display': ['Sidewalk'],
	'Obstruction|Sign': ['Sidewalk'],
	'Obstruction|Trash Or Recycling': ['Sidewalk', 'Street'],
	'Obstruction|Weeds Or Grass': ['Sidewalk'],
	'Outdoor Dining|Restaurant Status': ['Sidewalk'],
	'Outdoor Dining|Sidewalk Zone Blocked': ['Sidewalk'],
	'Outdoor Dining|Site Setup Condition': ['Sidewalk'],
	'Outside Building|Pavement': ['Residential Building'],
	'Outside Building|Roofing': ['Residential Building'],
	'Overgrown Tree/Branches|Blocking Street': ['Street'],
	'Overgrown Tree/Branches|Dead Branches In Tree': ['Street'],
	'Overgrown Tree/Branches|Hitting Building': ['Street'],
	'Overgrown Tree/Branches|Hitting Phone/Cable Lines': ['Street'],
	'Overgrown Tree/Branches|Hitting Power Lines': ['Street'],
	'Overgrown Tree/Branches|Traffic Sign Or Signal Blocked': ['Street'],
	'Paint/Plaster|Cabinet': ['Residential Building'],
	'Paint/Plaster|Ceiling': ['Residential Building'],
	'Paint/Plaster|Door/Frame': ['Residential Building'],
	'Paint/Plaster|Radiator': ['Residential Building'],
	'Paint/Plaster|Wall': ['Residential Building'],
	'Paint/Plaster|Window/Frame': ['Residential Building'],
	'Panhandling|UNKNOWN': [
		'Park/Playground',
		'Residential Building/House',
		'Store/Commercial',
		'Street/Sidewalk',
		'Subway'
	],
	'Plumbing|Basin/Sink': ['Residential Building'],
	'Plumbing|Bathtub/Shower': ['Residential Building'],
	'Plumbing|Failure To Retain Water/Improper Drainage- (Ll103/89)': ['UNKNOWN'],
	'Plumbing|Gas Hook-Up/Piping - Illegal Or Defective': ['UNKNOWN'],
	'Plumbing|Plumbing Work - Illegal/No Permit/Standpipe/Sprinkler': ['UNKNOWN'],
	'Plumbing|Plumbing-Defective/Leaking/Not Maintained': ['UNKNOWN'],
	'Plumbing|Radiator': ['Residential Building'],
	'Plumbing|Steam Pipe/Riser': ['Residential Building'],
	'Plumbing|Toilet': ['Residential Building'],
	'Plumbing|Water Supply': ['Residential Building'],
	'Real Time Enforcement|Work Without A Permit - Occupied Multiple Dwelling': ['UNKNOWN'],
	'Residential Disposal Complaint|Bin Not Used': ['Sidewalk', 'Street'],
	'Residential Disposal Complaint|Mattress Or Box Spring Uncovered': ['Sidewalk'],
	'Residential Disposal Complaint|Storage Area Not Provided': ['Sidewalk'],
	'Residential Disposal Complaint|Trash Or Recycling Not Secure': ['Sidewalk', 'Street'],
	'Residential Disposal Complaint|Waste Left In Front Of Other Residence': ['Sidewalk', 'Street'],
	'Residential Disposal Complaint|Waste Not Separated': ['Sidewalk', 'Street'],
	'Residential Disposal Complaint|Waste Set Out Too Early Or Too Late': ['Sidewalk', 'Street'],
	'Rodent|Condition Attracting Rodents': ['1-2 Family Dwelling', '3+ Family Apt. Building'],
	'Rodent|Rat Sighting': [
		'1-2 Family Dwelling',
		'3+ Family Apt. Building',
		'3+ Family Mixed Use Building',
		'Sidewalk'
	],
	'Rodent|Signs Of Rodents': ['3+ Family Apt. Building'],
	'Root/Sewer/Sidewalk Condition|Trees And Sidewalks Program': ['Street'],
	'Safety|Carbon Monoxide Detector': ['Residential Building'],
	'Safety|Fire Escape': ['Residential Building'],
	'Safety|Smoke Detector': ['Residential Building'],
	'Safety|Sprinkler': ['Residential Building'],
	'Safety|Window Guard Broken/Missing': ['Residential Building'],
	'Sanitation Worker Or Vehicle Complaint|Inappropriate Behavior': ['Street'],
	'Sanitation Worker Or Vehicle Complaint|Noise': ['Street'],
	'Sanitation Worker Or Vehicle Complaint|Spilled Garbage': ['Street'],
	'Sanitation Worker Or Vehicle Complaint|Unsafe Driving': ['Street'],
	'School Maintenance|Heating Problem': ['School'],
	'School Maintenance|Snow/Ice': ['School'],
	'Sewer|Catch Basin Clogged/Flooding (Use Comments) (Sc)': ['UNKNOWN'],
	'Sewer|Catch Basin Search (Sc2)': ['UNKNOWN'],
	'Sewer|Catch Basin Sunken/Damaged/Raised (Sc1)': ['UNKNOWN'],
	'Sewer|Culvert Blocked/Needs Cleaning (Se)': ['UNKNOWN'],
	'Sewer|Manhole Cover Missing (Emergency) (Sa3)': ['UNKNOWN'],
	'Sewer|Manhole Overflow (Use Comments) (Sa1)': ['UNKNOWN'],
	'Sewer|Rain Garden Debris (Girgd)': ['UNKNOWN'],
	'Sewer|Sewer Backup (Use Comments) (Sa)': ['UNKNOWN'],
	'Sewer|Sewer Odor (Sa2)': ['UNKNOWN'],
	'Sewer|Street Flooding (Sj)': ['UNKNOWN'],
	'Sidewalk Condition|Blocked - Construction': ['Sidewalk'],
	'Sidewalk Condition|Broken Sidewalk': ['Sidewalk'],
	'Sidewalk Condition|Defective Hardware': ['Sidewalk'],
	'Sidewalk Condition|Dumpster - Construction Waste': ['Sidewalk'],
	'Sidewalk Condition|Pedestrian Ramp Defective': ['Sidewalk'],
	'Sidewalk Condition|Sidewalk Collapsed': ['Sidewalk'],
	'Sidewalk Condition|Sidewalk Violation': ['Sidewalk'],
	'Smoking Or Vaping|Allowed In Smoke Free Area': [
		'Commercial Building',
		'Residential Building',
		'Restaurant/Bar/Deli/Bakery'
	],
	'Snow Or Ice|Pedestrian Feature': ['Street'],
	'Snow Or Ice|Roadway': ['Street'],
	'Snow Or Ice|Sidewalk': ['Sidewalk'],
	'Snow Or Ice|Snow Tracking': ['Street'],
	'Special Projects Inspection Team (Spit)|Advertising Sign/Billboard/Posters/Flexible Fabric - Illegal':
		['UNKNOWN'],
	'Special Projects Inspection Team (Spit)|Illegal Hotel Rooms In Residential Building': [
		'UNKNOWN'
	],
	'Special Projects Inspection Team (Spit)|Sign/Awning/Marquee - Illegal/No Permit': ['UNKNOWN'],
	'Street Condition|Blocked - Construction': ['Street'],
	'Street Condition|Cave-In': ['Street'],
	'Street Condition|Defective Hardware': ['Street'],
	'Street Condition|Dumpster - Construction Waste': ['Street'],
	'Street Condition|Failed Street Repair': ['Street'],
	'Street Condition|Plate Condition - Noisy': ['Street'],
	'Street Condition|Plate Condition - Shifted': ['Street'],
	'Street Condition|Pothole': ['UNKNOWN'],
	'Street Condition|Rough, Pitted Or Cracked Roads': ['Street'],
	'Street Light Condition|Fixture/Luminaire Hanging': ['UNKNOWN'],
	'Street Light Condition|Lamppost Base Door/Cover Open': ['UNKNOWN'],
	'Street Light Condition|Lamppost Damaged': ['UNKNOWN'],
	'Street Light Condition|Lamppost Knocked Down': ['UNKNOWN'],
	'Street Light Condition|Lamppost Wire Exposed': ['UNKNOWN'],
	'Street Light Condition|Multiple Street Lights Out': ['UNKNOWN'],
	'Street Light Condition|Street Light Cycling': ['UNKNOWN'],
	'Street Light Condition|Street Light Dayburning': ['UNKNOWN'],
	'Street Light Condition|Street Light Lamp Dim': ['UNKNOWN'],
	'Street Light Condition|Street Light Lamp Missing': ['UNKNOWN'],
	'Street Light Condition|Street Light Out': ['UNKNOWN'],
	'Street Light Condition|Traffic Signal Light': ['UNKNOWN'],
	'Street Sign - Damaged|Bus Stop': ['Street'],
	'Street Sign - Damaged|No Parking, Standing, Stopping': ['Street'],
	'Street Sign - Damaged|One Way': ['Street'],
	'Street Sign - Damaged|St Name - Attached To Pole': ['Street'],
	'Street Sign - Damaged|Stop': ['Street'],
	'Street Sign - Damaged|Street Cleaning - Asp': ['Street'],
	'Street Sign - Damaged|UNKNOWN': ['Street'],
	'Street Sign - Dangling|No Parking, Standing, Stopping': ['Street'],
	'Street Sign - Dangling|St Name - Attached To Pole': ['Street'],
	'Street Sign - Dangling|Stop': ['Street'],
	'Street Sign - Dangling|Street Cleaning - Asp': ['Street'],
	'Street Sign - Dangling|UNKNOWN': ['Street'],
	'Street Sign - Missing|No Parking, Standing, Stopping': ['Street'],
	'Street Sign - Missing|St Name - Attached To Pole': ['Street'],
	'Street Sign - Missing|Stop': ['Street'],
	'Street Sign - Missing|UNKNOWN': ['Street'],
	'Street Sweeping Complaint|Inadequate Sweeping': ['Street'],
	'Street Sweeping Complaint|Street Not Swept': ['Street'],
	'Taxi Complaint|Driver Complaint - Non Passenger': ['Street'],
	'Taxi Complaint|Driver Complaint - Passenger': ['Street'],
	'Traffic Signal Condition|Aps': ['UNKNOWN'],
	'Traffic Signal Condition|Base Door': ['UNKNOWN'],
	'Traffic Signal Condition|Bike Signal': ['UNKNOWN'],
	'Traffic Signal Condition|Cable': ['UNKNOWN'],
	'Traffic Signal Condition|Controller': ['UNKNOWN'],
	'Traffic Signal Condition|Led Pedestrian Unit': ['UNKNOWN'],
	'Traffic Signal Condition|Ped Lamp': ['UNKNOWN'],
	'Traffic Signal Condition|Ped Multiple Lamps': ['UNKNOWN'],
	'Traffic Signal Condition|Pedestrian Signal': ['UNKNOWN'],
	'Traffic Signal Condition|Post': ['UNKNOWN'],
	'Traffic Signal Condition|Time Switch': ['UNKNOWN'],
	'Traffic Signal Condition|Underground': ['UNKNOWN'],
	'Traffic Signal Condition|Veh Sgnl Mult Lamps': ['UNKNOWN'],
	'Traffic Signal Condition|Veh Signal Head': ['UNKNOWN'],
	'Traffic Signal Condition|Veh Signal Lamp': ['UNKNOWN'],
	'Traffic Signal Condition|Veh Signal Lens': ['UNKNOWN'],
	'Traffic Signal Condition|Veh Signal Visor': ['UNKNOWN'],
	'Traffic Signal Condition|Vehicle Signal': ['UNKNOWN'],
	'Traffic Signal Condition|Wireless': ['UNKNOWN'],
	'Traffic|Chronic Speeding': ['Street/Sidewalk'],
	'Traffic|Chronic Stoplight Violation': ['Street/Sidewalk'],
	'Traffic|Congestion/Gridlock': ['Street/Sidewalk'],
	'Traffic|Drag Racing': ['Street/Sidewalk'],
	'Traffic|Truck Route Violation': ['Street/Sidewalk'],
	'Unleashed Dog|Unleashed Dog In Public': ['Public/Unfenced Area'],
	'Unsanitary Animal Pvt Property|Dog': ['3+ Family Apartment Building'],
	'Unsanitary Condition|Garbage/Recycling Storage': ['Residential Building'],
	'Unsanitary Condition|Mold': ['Residential Building'],
	'Unsanitary Condition|Pests': ['Residential Building'],
	'Unsanitary Condition|Sewage': ['Residential Building'],
	'Urinating In Public|UNKNOWN': ['Residential Building/House', 'Street/Sidewalk'],
	'Vendor Enforcement|Food Vendor': ['Street'],
	'Vendor Enforcement|Non-Food Vendor': ['Street'],
	'Violation Of Park Rules|Bbq Outside Authorized Area': ['Park'],
	'Violation Of Park Rules|Obstructing Public Use': ['Park'],
	'Violation Of Park Rules|Smoking': ['Park'],
	'Violation Of Park Rules|Unlicensed Vendors': ['Park'],
	'Violation Of Park Rules|Unsafe Use Of Playground': ['Park'],
	'Water Conservation|Illegal Use Of A Hydrant (Cin)': ['UNKNOWN'],
	'Water Conservation|Water Meter Broken/Leaking - Other (Cmo)': ['UNKNOWN'],
	'Water Conservation|Water Meter Broken/Leaking - Private Residence (Cmr)': ['UNKNOWN'],
	'Water Leak|Damp Spot': ['Residential Building'],
	'Water Leak|Heavy Flow': ['Residential Building'],
	'Water Leak|Slow Leak': ['Residential Building'],
	'Water System|Dirty Water (We)': ['UNKNOWN'],
	'Water System|Excessive Water In Basement (Wefb)': ['UNKNOWN'],
	'Water System|Hyd Valve Box Cover Missing (Wv2)': ['UNKNOWN'],
	'Water System|Hydrant Defective (Wc2)': ['UNKNOWN'],
	'Water System|Hydrant Knocked Over/Missing (Wc)': ['UNKNOWN'],
	'Water System|Hydrant Leaking (Wc1)': ['UNKNOWN'],
	'Water System|Hydrant Running (Wc3)': ['UNKNOWN'],
	'Water System|Hydrant Running Full (Wa4)': ['UNKNOWN'],
	'Water System|Leak (Use Comments) (Wa2)': ['UNKNOWN'],
	'Water System|Low Water Pressure - Wlwp': ['UNKNOWN'],
	'Water System|No Water (Wnw)': ['UNKNOWN'],
	'Water System|Possible Water Main Break (Use Comments) (Wa1)': ['UNKNOWN'],
	'Wood Pile Remaining|Remove Debris': ['Street']
};

// export const COMPLAINT_LOCATIONS: Record<string, string[]> = {
//     'Abandoned Bike': ['Street'],
//     'Abandoned Vehicle': ['Street/Sidewalk'],
//     'Air Quality': ['UNKNOWN'],
//     'Animal In A Park': ['Park'],
//     'Animal-Abuse': ['House And Store', 'Residential Building', 'Residential Building/House', 'Store/Commercial', 'Street/Sidewalk'],
//     'Appliance': ['Residential Building'],
//     'Asbestos': ['3+ Family Apartment Building', 'UNKNOWN'],
//     'Best/Site Safety': ['UNKNOWN'],
//     'Bike Rack': ['Sidewalk'],
//     'Bike/Roller/Skate': ['Street/Sidewalk'],
//     'Bike/Roller/Skate Chronic': ['Street/Sidewalk'],
//     'Blocked Driveway': ['Street/Sidewalk'],
//     'Boilers': ['UNKNOWN'],
//     'Broken Parking Meter': ['Street'],
//     'Building/Use': ['UNKNOWN'],
//     'Bus Stop Shelter Complaint': ['Bus Stop Shelter'],
//     'Bus Stop Shelter Placement': ['Bus Stop Shelter'],
//     'Cannabis Retailer': ['UNKNOWN'],
//     'Commercial Disposal Complaint': ['Sidewalk'],
//     'Consumer Complaint': ['Business'],
//     'Curb Condition': ['Curb', 'Sidewalk'],
//     'Damaged Tree': ['Street'],
//     'Day Care': ['Apartment', 'Commercial Building', 'OTHER', 'Private School'],
//     'Dead Animal': ['Sidewalk', 'Street'],
//     'Dead/Dying Tree': ['Street'],
//     'Derelict Vehicles': ['Street'],
//     'Dirty Condition': ['Alley', 'Gutter', 'Sidewalk', 'Street', 'Yard'],
//     'Door/Window': ['Residential Building'],
//     'Drinking': ['Club/Bar/Restaurant', 'Residential Building/House', 'Store/Commercial', 'Street/Sidewalk'],
//     'Drug Activity': ['Common Area', 'Hallway', 'Lobby', 'OTHER', 'Stairwell', 'Street/Sidewalk'],
//     'Dumpster Complaint': ['Sidewalk', 'Street'],
//     'Electric': ['Residential Building'],
//     'Electrical': ['UNKNOWN'],
//     'Elevator': ['Residential Building', 'UNKNOWN'],
//     'Emergency Response Team (Ert)': ['UNKNOWN'],
//     'Encampment': ['Park/Playground', 'Residential Building/House', 'Store/Commercial', 'Street/Sidewalk', 'Subway'],
//     'Flooring/Stairs': ['Residential Building'],
//     'Food Establishment': ['Restaurant/Bar/Deli/Bakery'],
//     'Food Poisoning': ['OTHER', 'Restaurant/Bar/Deli/Bakery'],
//     'For Hire Vehicle Complaint': ['Street', 'UNKNOWN'],
//     'General': ['Residential Building'],
//     'General Construction/Plumbing': ['UNKNOWN'],
//     'Graffiti': ['Comercial', 'Mixed Use', 'Residential', 'Store/Commercial', 'Street/Sidewalk', 'UNKNOWN'],
//     'Hazardous Materials': ['UNKNOWN'],
//     'Heat/Hot Water': ['Residential Building'],
//     'Homeless Person Assistance': ['House Of Worship', 'OTHER', 'Park/Playground', 'Residential Building/House', 'Store/Commercial', 'Street/Sidewalk', 'Subway'],
//     'Illegal Dumping': ['Sidewalk', 'Street'],
//     'Illegal Fireworks': ['Park/Playground', 'Residential Building/House', 'Street/Sidewalk'],
//     'Illegal Parking': ['Street/Sidewalk'],
//     'Illegal Posting': ['Sidewalk', 'Street'],
//     'Illegal Tree Damage': ['Street'],
//     'Indoor Air Quality': ['1-2 Family Dwelling', '3+ Family Apartment Building', '3+ Family Apt. Building'],
//     'Indoor Sewage': ['3+ Family Apt. Building'],
//     'Investigations And Discipline (Iad)': ['UNKNOWN'],
//     'Lead': ['UNKNOWN'],
//     'Litter Basket Complaint': ['Sidewalk'],
//     'Litter Basket Request': ['Sidewalk', 'Street'],
//     'Lost Property': ['Taxi'],
//     'Maintenance Or Facility': ['Park', 'Street/Curbside'],
//     'Missed Collection': ['Street'],
//     'Mobile Food Vendor': ['Mobile Food Vendor'],
//     'Mold': ['Commercial Building'],
//     'New Tree Request': ['Street'],
//     'Noise': ['UNKNOWN'],
//     'Noise - Commercial': ['Club/Bar/Restaurant', 'Store/Commercial'],
//     'Noise - House Of Worship': ['House Of Worship'],
//     'Noise - Park': ['Park/Playground'],
//     'Noise - Residential': ['Residential Building/House'],
//     'Noise - Street/Sidewalk': ['Street/Sidewalk'],
//     'Noise - Vehicle': ['Street/Sidewalk'],
//     'Non-Emergency Police Matter': ['Park/Playground', 'Residential Building/House', 'Store/Commercial', 'Street/Sidewalk'],
//     'Non-Residential Heat': ['Building (Non-Residential)'],
//     'Obstruction': ['Sidewalk', 'Street'],
//     'Outdoor Dining': ['Sidewalk'],
//     'Outside Building': ['Residential Building'],
//     'Overgrown Tree/Branches': ['Street'],
//     'Paint/Plaster': ['Residential Building'],
//     'Panhandling': ['Park/Playground', 'Residential Building/House', 'Store/Commercial', 'Street/Sidewalk', 'Subway'],
//     'Plumbing': ['Residential Building', 'UNKNOWN'],
//     'Real Time Enforcement': ['UNKNOWN'],
//     'Residential Disposal Complaint': ['Sidewalk', 'Street'],
//     'Rodent': ['1-2 Family Dwelling', '3+ Family Apt. Building', '3+ Family Mixed Use Building', 'Sidewalk'],
//     'Root/Sewer/Sidewalk Condition': ['Street'],
//     'Safety': ['Residential Building'],
//     'Sanitation Worker Or Vehicle Complaint': ['Street'],
//     'School Maintenance': ['School'],
//     'Sewer': ['UNKNOWN'],
//     'Sidewalk Condition': ['Sidewalk'],
//     'Smoking Or Vaping': ['Commercial Building', 'Residential Building', 'Restaurant/Bar/Deli/Bakery'],
//     'Snow Or Ice': ['Sidewalk', 'Street'],
//     'Special Projects Inspection Team (Spit)': ['UNKNOWN'],
//     'Street Condition': ['Street', 'UNKNOWN'],
//     'Street Light Condition': ['UNKNOWN'],
//     'Street Sign - Damaged': ['Street'],
//     'Street Sign - Dangling': ['Street'],
//     'Street Sign - Missing': ['Street'],
//     'Street Sweeping Complaint': ['Street'],
//     'Taxi Complaint': ['Street'],
//     'Traffic': ['Street/Sidewalk'],
//     'Traffic Signal Condition': ['UNKNOWN'],
//     'Unleashed Dog': ['Public/Unfenced Area'],
//     'Unsanitary Animal Pvt Property': ['3+ Family Apartment Building'],
//     'Unsanitary Condition': ['Residential Building'],
//     'Urinating In Public': ['Residential Building/House', 'Street/Sidewalk'],
//     'Vendor Enforcement': ['Street'],
//     'Violation Of Park Rules': ['Park'],
//     'Water Conservation': ['UNKNOWN'],
//     'Water Leak': ['Residential Building'],
//     'Water System': ['UNKNOWN'],
//     'Wood Pile Remaining': ['Street'],
// };
