export const AGENCIES = [
    'DCWP',
    'DEP',
    'DHS',
    'DOB',
    'DOE',
    'DOHMH',
    'DOT',
    'DPR',
    'DSNY',
    'HPD',
    'NYC311-PRD',
    'NYPD',
    'OOS',
    'TLC'
] as const;

export const AGENCY_NAMES: Record<string, string> = {
    DCWP: 'Department of Consumer and Worker Protection',
    DEP: 'Department of Environmental Protection',
    DHS: 'Department of Homeless Services',
    DOB: 'Department of Buildings',
    DOE: 'Department of Education',
    DOHMH: 'Department of Health and Mental Hygiene',
    DOT: 'Department of Transportation',
    DPR: 'Department of Parks and Recreation',
    DSNY: 'Department of Sanitation',
    HPD: 'Department of Housing Preservation and Development',
    'NYC311-PRD': 'Highway Inspection and Quality Assurance',
    NYPD: 'New York City Police Department',
    OOS: 'Office of the Sheriff',
    TLC: 'Taxi and Limousine Commission'
};

export const COMPLAINT_TYPES = [
    'Abandoned Bike',
    'Abandoned Vehicle',
    'Air Quality',
    'Animal In A Park',
    'Animal-Abuse',
    'Appliance',
    'Asbestos',
    'Best/Site Safety',
    'Bike Rack',
    'Bike/Roller/Skate',
    'Bike/Roller/Skate Chronic',
    'Blocked Driveway',
    'Boilers',
    'Broken Parking Meter',
    'Building/Use',
    'Bus Stop Shelter Complaint',
    'Bus Stop Shelter Placement',
    'Cannabis Retailer',
    'Commercial Disposal Complaint',
    'Consumer Complaint',
    'Curb Condition',
    'Damaged Tree',
    'Day Care',
    'Dead Animal',
    'Dead/Dying Tree',
    'Derelict Vehicles',
    'Dirty Condition',
    'Door/Window',
    'Drinking',
    'Drug Activity',
    'Dumpster Complaint',
    'Electric',
    'Electrical',
    'Elevator',
    'Emergency Response Team (Ert)',
    'Encampment',
    'Flooring/Stairs',
    'Food Establishment',
    'Food Poisoning',
    'For Hire Vehicle Complaint',
    'General',
    'General Construction/Plumbing',
    'Graffiti',
    'Hazardous Materials',
    'Heat/Hot Water',
    'Homeless Person Assistance',
    'Illegal Dumping',
    'Illegal Fireworks',
    'Illegal Parking',
    'Illegal Posting',
    'Illegal Tree Damage',
    'Indoor Air Quality',
    'Indoor Sewage',
    'Investigations And Discipline (Iad)',
    'Lead',
    'Litter Basket Complaint',
    'Litter Basket Request',
    'Lost Property',
    'Maintenance Or Facility',
    'Missed Collection',
    'Mobile Food Vendor',
    'Mold',
    'New Tree Request',
    'Noise',
    'Noise - Commercial',
    'Noise - House Of Worship',
    'Noise - Park',
    'Noise - Residential',
    'Noise - Street/Sidewalk',
    'Noise - Vehicle',
    'Non-Emergency Police Matter',
    'Non-Residential Heat',
    'Obstruction',
    'Outdoor Dining',
    'Outside Building',
    'Overgrown Tree/Branches',
    'Paint/Plaster',
    'Panhandling',
    'Plumbing',
    'Real Time Enforcement',
    'Residential Disposal Complaint',
    'Rodent',
    'Root/Sewer/Sidewalk Condition',
    'Safety',
    'Sanitation Worker Or Vehicle Complaint',
    'School Maintenance',
    'Sewer',
    'Sidewalk Condition',
    'Smoking Or Vaping',
    'Snow Or Ice',
    'Special Projects Inspection Team (Spit)',
    'Street Condition',
    'Street Light Condition',
    'Street Sign - Damaged',
    'Street Sign - Dangling',
    'Street Sign - Missing',
    'Street Sweeping Complaint',
    'Taxi Complaint',
    'Traffic',
    'Traffic Signal Condition',
    'Unleashed Dog',
    'Unsanitary Animal Pvt Property',
    'Unsanitary Condition',
    'Urinating In Public',
    'Vendor Enforcement',
    'Violation Of Park Rules',
    'Water Conservation',
    'Water Leak',
    'Water System',
    'Wood Pile Remaining'
] as const;
