export const AGENCIES = [
    'DCWP',
    'DEP',
    'DHS',
    'DOB',
    'DOE',
    'DOHMH',
    'DOT',
    'DPR',
    'DSNY',
    'HPD',
    'NYC311-PRD',
    'NYPD',
    'OOS',
    'TLC'
] as const;

export const AGENCY_NAMES: Record<string, string> = {
    DCWP: 'Department of Consumer and Worker Protection',
    DEP: 'Department of Environmental Protection',
    DHS: 'Department of Homeless Services',
    DOB: 'Department of Buildings',
    DOE: 'Department of Education',
    DOHMH: 'Department of Health and Mental Hygiene',
    DOT: 'Department of Transportation',
    DPR: 'Department of Parks and Recreation',
    DSNY: 'Department of Sanitation',
    HPD: 'Department of Housing Preservation and Development',
    'NYC311-PRD': 'Highway Inspection and Quality Assurance',
    NYPD: 'New York City Police Department',
    OOS: 'Office of the Sheriff',
    TLC: 'Taxi and Limousine Commission'
};

export const BOROUGHS = [
    'BRONX',
    'BROOKLYN',
    'MANHATTAN',
    'QUEENS',
    'STATEN ISLAND',
    'Unspecified'
] as const;

export const LOCATION_TYPES = [
    '1-2 Family Dwelling',
    '3+ Family Apartment Building',
    '3+ Family Apt. Building',
    '3+ Family Mixed Use Building',
    'Alley',
    'Apartment',
    'Building (Non-Residential)',
    'Bus Stop Shelter',
    'Business',
    'Club/Bar/Restaurant',
    'Comercial',
    'Commercial Building',
    'Common Area',
    'Curb',
    'Gutter',
    'Hallway',
    'House And Store',
    'House Of Worship',
    'Lobby',
    'Mixed Use',
    'Mobile Food Vendor',
    'OTHER',
    'Park',
    'Park/Playground',
    'Private School',
    'Public/Unfenced Area',
    'Residential',
    'Residential Building',
    'Residential Building/House',
    'Restaurant/Bar/Deli/Bakery',
    'School',
    'Sidewalk',
    'Stairwell',
    'Store/Commercial',
    'Street',
    'Street/Curbside',
    'Street/Sidewalk',
    'Subway',
    'Taxi',
    'UNKNOWN',
    'Yard'
] as const;

export const COMPLAINT_TYPES = [
    'Abandoned Bike',
    'Abandoned Vehicle',
    'Air Quality',
    'Animal In A Park',
    'Animal-Abuse',
    'Appliance',
    'Asbestos',
    'Best/Site Safety',
    'Bike Rack',
    'Bike/Roller/Skate',
    'Bike/Roller/Skate Chronic',
    'Blocked Driveway',
    'Boilers',
    'Broken Parking Meter',
    'Building/Use',
    'Bus Stop Shelter Complaint',
    'Bus Stop Shelter Placement',
    'Cannabis Retailer',
    'Commercial Disposal Complaint',
    'Consumer Complaint',
    'Curb Condition',
    'Damaged Tree',
    'Day Care',
    'Dead Animal',
    'Dead/Dying Tree',
    'Derelict Vehicles',
    'Dirty Condition',
    'Door/Window',
    'Drinking',
    'Drug Activity',
    'Dumpster Complaint',
    'Electric',
    'Electrical',
    'Elevator',
    'Emergency Response Team (Ert)',
    'Encampment',
    'Flooring/Stairs',
    'Food Establishment',
    'Food Poisoning',
    'For Hire Vehicle Complaint',
    'General',
    'General Construction/Plumbing',
    'Graffiti',
    'Hazardous Materials',
    'Heat/Hot Water',
    'Homeless Person Assistance',
    'Illegal Dumping',
    'Illegal Fireworks',
    'Illegal Parking',
    'Illegal Posting',
    'Illegal Tree Damage',
    'Indoor Air Quality',
    'Indoor Sewage',
    'Investigations And Discipline (Iad)',
    'Lead',
    'Litter Basket Complaint',
    'Litter Basket Request',
    'Lost Property',
    'Maintenance Or Facility',
    'Missed Collection',
    'Mobile Food Vendor',
    'Mold',
    'New Tree Request',
    'Noise',
    'Noise - Commercial',
    'Noise - House Of Worship',
    'Noise - Park',
    'Noise - Residential',
    'Noise - Street/Sidewalk',
    'Noise - Vehicle',
    'Non-Emergency Police Matter',
    'Non-Residential Heat',
    'Obstruction',
    'Outdoor Dining',
    'Outside Building',
    'Overgrown Tree/Branches',
    'Paint/Plaster',
    'Panhandling',
    'Plumbing',
    'Real Time Enforcement',
    'Residential Disposal Complaint',
    'Rodent',
    'Root/Sewer/Sidewalk Condition',
    'Safety',
    'Sanitation Worker Or Vehicle Complaint',
    'School Maintenance',
    'Sewer',
    'Sidewalk Condition',
    'Smoking Or Vaping',
    'Snow Or Ice',
    'Special Projects Inspection Team (Spit)',
    'Street Condition',
    'Street Light Condition',
    'Street Sign - Damaged',
    'Street Sign - Dangling',
    'Street Sign - Missing',
    'Street Sweeping Complaint',
    'Taxi Complaint',
    'Traffic',
    'Traffic Signal Condition',
    'Unleashed Dog',
    'Unsanitary Animal Pvt Property',
    'Unsanitary Condition',
    'Urinating In Public',
    'Vendor Enforcement',
    'Violation Of Park Rules',
    'Water Conservation',
    'Water Leak',
    'Water System',
    'Wood Pile Remaining'
] as const;

export const DESCRIPTORS = [
    '1 Or 2',
    '3 Or More',
    'Abandoned Bike',
    'Adjacent Buildings Not Protected',
    'Advertising Sign/Billboard/Posters/Flexible Fabric - Illegal',
    'After Hours - Licensed Est',
    'After Hours Work - Illegal',
    'Air: Dust, Construction/Demolition (Ae4)',
    'Air: Odor/Fumes, Restaurant (Ad2)',
    'Air: Odor/Fumes, Vehicle Idling (Ad3)',
    'Air: Other Air Problem (Use Comments) (Azz)',
    'Air: Smoke, Chimney Or Vent (As1)',
    'Air: Smoke, Vehicular (Aa4)',
    'Allowed In Smoke Free Area',
    'Apartment Only',
    'Aps',
    'Asbestos Complaint (B1)',
    'Bag/Wallet',
    'Banging/Pounding',
    'Barber Shop, Beauty Salon, Or Nail Salon',
    'Bare Hands In Contact W/ Food',
    'Base Door',
    'Basin/Sink',
    'Bathtub/Shower',
    'Bbq Outside Authorized Area',
    'Bell/Buzzer/Intercom',
    'Bicycle Chained To Tree',
    'Bike Signal',
    'Bin Not Used',
    'Bird',
    'Blocked - Construction',
    'Blocked Bike Lane',
    'Blocked Crosswalk',
    'Blocked Hydrant',
    'Blocked Sidewalk',
    'Blocking Sidewalk Or Street',
    'Blocking Street',
    'Bodega, Deli, Or Convenience Store',
    'Boiler - Defective/Inoperative/No Permit',
    'Branch Cracked And Will Fall',
    'Branch Or Limb Has Fallen Down',
    'Branches Damaged',
    'Broken Curb',
    'Broken Glass',
    'Broken Sidewalk',
    'Building - Vacant, Open And Unguarded',
    'Building Permit - None',
    'Building Shaking/Vibrating/Structural Stability',
    'Bulky Recycling',
    'Bulky Trash',
    'Bus Stop',
    'Cabinet',
    'Cable',
    'Car Wash',
    'Car/Truck Horn',
    'Car/Truck Music',
    'Carbon Monoxide Detector',
    'Cat',
    'Catch Basin Clogged/Flooding (Use Comments) (Sc)',
    'Catch Basin Search (Sc2)',
    'Catch Basin Sunken/Damaged/Raised (Sc1)',
    'Cave-In',
    'Ceiling',
    'Chained',
    'Chained To Public Property',
    'Chemical Odor (Hd1)',
    'Chemical Spill/Release (Ha1)',
    'Chemical Vapors/Gases/Odors',
    'Chronic',
    'Chronic Dumping',
    'Chronic Speeding',
    'Chronic Stoplight Violation',
    'Clothing, Shoe, Or Accessories Store',
    'Clothing/Glasses',
    'Coin Or Card Did Not Register',
    'Commercial Overnight Parking',
    'Compost',
    'Condition Attracting Rodents',
    'Cone',
    'Congestion/Gridlock',
    'Cons - Contrary/Beyond Approved Plans/Permits',
    'Controller',
    'Cooking Gas',
    'Culvert Blocked/Needs Cleaning (Se)',
    'Curb Cut/Driveway/Carport - Illegal',
    'Curb Defect-Metal Protruding',
    'Damp Spot',
    'Day Care Facility',
    'Dead Animal',
    'Dead Branches In Tree',
    'Debris - Excessive',
    'Debris - Falling Or In Danger Of Falling',
    'Debris From Car Accident',
    'Defacement',
    'Defective Hardware',
    'Demolition - Unsafe',
    'Derelict Vehicles',
    'Detached Trailer',
    'Dirt Or Gravel',
    'Dirty Water (We)',
    'Dirty/Graffiti',
    'Dog',
    'Dog Off Leash',
    'Dog Waste',
    'Door',
    'Door Frame',
    'Door/Frame',
    'Double Parked Blocking Traffic',
    'Double Parked Blocking Vehicle',
    'Drag Racing',
    'Driver Complaint - Non Passenger',
    'Driver Complaint - Passenger',
    'Drug Store Or Pharmacy',
    'Dumpster - Construction Waste',
    'Dust From Construction',
    'Egress - Doors Locked/Blocked/Improper/No Secondary Means',
    'Electric/Gas Range',
    'Electrical Wiring Defective/Exposed',
    'Electronics/Phones',
    'Elevator - Multiple Devices On Property',
    'Elevator - Single Device On Property/No Alternate Service',
    'Engine Idling',
    'Entire Building',
    'Entire Tree Has Fallen Down',
    'Equipment',
    'Excessive Water In Basement (Wefb)',
    'Failed Street Repair',
    'Failure To Maintain',
    'Failure To Retain Water/Improper Drainage- (Ll103/89)',
    'Fence - None/Inadequate',
    'Fire Escape',
    'Fixture/Luminaire Hanging',
    'Floor',
    'Flyer Or Handbill',
    'Food Contains Foreign Object',
    'Food Contaminated',
    'Food Source/Protection',
    'Food Spoiled',
    'Food Temperature',
    'Food Vendor',
    'Food Worker Activity',
    'Food Worker Hygiene',
    'For One Address',
    'Garage Or Parking Lot',
    'Garbage Or Litter',
    'Garbage/Recycling Storage',
    'Gas Hook-Up/Piping - Illegal Or Defective',
    'Graffiti',
    'Graffiti Or Vandalism',
    'Grass/Weeds',
    'Heating Problem',
    'Heavy Flow',
    'Hitting Building',
    'Hitting Phone/Cable Lines',
    'Hitting Power Lines',
    'Home Improvement Contractor',
    'Hotel Or Motel',
    'Hours Of Operation',
    'Hyd Valve Box Cover Missing (Wv2)',
    'Hydrant Defective (Wc2)',
    'Hydrant Knocked Over/Missing (Wc)',
    'Hydrant Leaking (Wc1)',
    'Hydrant Running (Wc3)',
    'Hydrant Running Full (Wa4)',
    'Illegal Conversion Of Residential Building/Space',
    'Illegal Hotel Rooms In Residential Building',
    'Illegal Use Of A Hydrant (Cin)',
    'Illegal. Commercial Use In Resident Zone',
    'In Public',
    'Inadequate Or No Heat',
    'Inadequate Sweeping',
    'Inappropriate Behavior',
    'Injured Wildlife',
    'Investigative Inspection',
    'Janitor/Super',
    'Kitchen/Food Prep Area',
    'Lamppost Base Door/Cover Open',
    'Lamppost Damaged',
    'Lamppost Knocked Down',
    'Lamppost Wire Exposed',
    'Landlord Or Real Estate Agent',
    'Laundromat',
    'Lead Kit Request (Residential) (L10)',
    'Leak (Use Comments) (Wa2)',
    'Led Pedestrian Unit',
    'Letter Grading',
    'License Plate Obscured',
    'Lighting',
    'Lights From Parking Lot Shining On Building',
    'Loud Music/Party',
    'Loud Talking',
    'Loud Television',
    'Low Water Pressure - Wlwp',
    'Mailbox',
    'Maintenance',
    'Manhole Cover Missing (Emergency) (Sa3)',
    'Manhole Overflow (Use Comments) (Sa1)',
    'Mattress Or Box Spring Uncovered',
    'Merchandise',
    'Mold',
    'Multiple Street Lights Out',
    'Neglected',
    'New Basket',
    'New Bus Stop Shelter Placement',
    'No Access',
    'No Certificate Of Occupancy/Illegal/Contrary To Co',
    'No Lighting',
    'No Parking, Standing, Stopping',
    'No Permit Or License',
    'No Receipt',
    'No Shelter',
    'No Water (Wnw)',
    'Noise',
    'Noise, Barking Dog (Nr5)',
    'Noise, Ice Cream Truck (Nr4)',
    'Noise, Other Animals (Nr6)',
    'Noise:  Lawn Care Equipment (Ncl)',
    'Noise: Air Condition/Ventilation Equipment (Nv1)',
    'Noise: Alarms (Nr3)',
    'Noise: Boat(Engine,Music,Etc) (Nr10)',
    'Noise: Construction Before/After Hours (Nm1)',
    'Noise: Construction Equipment (Nc1)',
    'Noise: Jack Hammering (Nc2)',
    'Noise: Manufacturing Noise (Nk1)',
    'Noise: Private Carting Noise (Nq1)',
    'Non-Chronic',
    'Non-Food Vendor',
    'OTHER',
    'Obstructing Public Use',
    'One Way',
    'Opossum',
    'Other Store (Non-Food)',
    'Out Of Order',
    'Outlet/Switch',
    'Overflowing',
    'Overflowing Dumpster',
    'Overnight Commercial Storage',
    'Paper License Plates',
    'Parking Permit Improper Use',
    'Partial Access',
    'Pavement',
    'Ped Lamp',
    'Ped Multiple Lamps',
    'Pedestrian Feature',
    'Pedestrian Ramp Defective',
    'Pedestrian Signal',
    'Pests',
    'Pet/Animal',
    'Planted Less Than 2 Years Ago',
    'Planted More Than 2 Years Ago',
    'Plate Condition - Noisy',
    'Plate Condition - Shifted',
    'Plumbing Work - Illegal/No Permit/Standpipe/Sprinkler',
    'Plumbing-Defective/Leaking/Not Maintained',
    'Police Report Not Requested',
    'Possible Water Main Break (Use Comments) (Wa1)',
    'Post',
    'Posted Notice Or Order Removed/Tampered With',
    'Posted Parking Sign Violation',
    'Poster Or Sign',
    'Pothole',
    'Power Outage',
    'Public Complaint - Comm Location',
    'Raccoon',
    'Radiator',
    'Rain Garden Debris (Girgd)',
    'Rat Or Mouse',
    'Rat Sighting',
    'Recycling - Metal/Glass/Rigid Plastic',
    'Recycling - Paper',
    'Recycling - Paper/Metal/Glass/Rigid Plastic',
    'Refrigerator',
    'Removal Request',
    'Remove Debris',
    'Replacement Basket',
    'Restaurant',
    'Restaurant Status',
    'Roadway',
    'Rodent Sighting',
    'Rodents/Insects/Garbage',
    'Roofing',
    'Roots Damaged',
    'Rough, Pitted Or Cracked Roads',
    'Sales To Minors Under 21',
    'Sewage',
    'Sewage Leak',
    'Sewage Odor',
    'Sewer Backup (Use Comments) (Sa)',
    'Sewer Odor (Sa2)',
    'Sidewalk',
    'Sidewalk Collapsed',
    'Sidewalk Display',
    'Sidewalk Shed/Pipe Scafford - Inadequate Defective/None',
    'Sidewalk Violation',
    'Sidewalk Zone Blocked',
    'Sign',
    'Sign/Awning/Marquee - Illegal/No Permit',
    'Signage Missing',
    'Signs Of Rodents',
    'Site Conditions Endangering Workers',
    'Site Setup Condition',
    'Slow Leak',
    'Smoke Detector',
    'Smoking',
    'Snow Or Ice',
    'Snow Removal Requested',
    'Snow Tracking',
    'Snow/Ice',
    'Spilled Garbage',
    'Sprinkler',
    'Squirrel',
    'Sro - Illegal Work/No Permit/Change In Occupancy/Use',
    'St Name - Attached To Pole',
    'Stairs',
    'Steam Pipe/Riser',
    'Sticker Or Decal',
    'Stoop Line Stand',
    'Stop',
    'Storage Area Not Provided',
    'Storage Warehouse',
    'Street Cleaning - Asp',
    'Street Fair Vendor',
    'Street Flooding (Sj)',
    'Street Light Cycling',
    'Street Light Dayburning',
    'Street Light Lamp Dim',
    'Street Light Lamp Missing',
    'Street Light Out',
    'Street Not Swept',
    'Structure - Indoors',
    'Structure - Outdoors',
    'Supermarket Or Grocery Store',
    'Suspicious Activity',
    'Syringes',
    'Time Switch',
    'Tobacco Sales',
    'Toilet',
    'Tortured',
    'Tow Truck Company',
    'Traffic Sign Or Signal Blocked',
    'Traffic Signal Light',
    'Trash',
    'Trash And Bulky Trash',
    'Trash Or Recycling',
    'Trash Or Recycling Not Secure',
    'Tree Alive - In Poor Condition',
    'Tree Leaning/Uprooted',
    'Tree Trunk Split',
    'Trees And Sidewalks Program',
    'Trespassing',
    'Truck Route Violation',
    'Trunk Damaged',
    'UNKNOWN',
    'Unauthorized Bus Layover',
    'Unauthorized Tree Pruning',
    'Unauthorized Tree Removal',
    'Underage - Licensed Est',
    'Underground',
    'Unleashed Dog In Public',
    'Unlicensed',
    'Unlicensed Vendors',
    'Unsafe Driving',
    'Unsafe Use Of Playground',
    'Unsecured Facility',
    'Use Indoor',
    'Use Outside',
    'Used Car Dealer',
    'Veh Sgnl Mult Lamps',
    'Veh Signal Head',
    'Veh Signal Lamp',
    'Veh Signal Lens',
    'Veh Signal Visor',
    'Vehicle Signal',
    'Vent/Exhaust - Illegal/Improper',
    'Ventilation',
    'Ventilation System',
    'Wall',
    'Wall/Retaining Wall - Bulging/Cracked',
    'Waste Disposal',
    'Waste Left In Front Of Other Residence',
    'Waste Left In Front Of Residence',
    'Waste Not Separated',
    'Waste Set Out Too Early Or Too Late',
    'Water Meter Broken/Leaking - Other (Cmo)',
    'Water Meter Broken/Leaking - Private Residence (Cmr)',
    'Water Supply',
    'Weeds Or Grass',
    'Window Frame',
    'Window Guard Broken/Missing',
    'Window Pane',
    'Window/Frame',
    'Wireless',
    'Wiring',
    'With License Plate',
    'Work Without A Permit - Occupied Multiple Dwelling',
    'Working Contrary To Stop Work Order',
    'Zoning - Non-Conforming/Illegal Vehicle Storage'
] as const;
